---
 - name: Install Apache2 or Httpd and upload html
   hosts: dev_redblue_servers
   become: yes

   roles:
   #  - { role: deploy_apache_web, when: ansible_system == "Linux" }
     - deploy_apache_web
