---
# tasks file for deploy_apache_web

 - block: #Debian BLock

   - name: Install Apache2 Web Server to Ubuntu
     apt: name=apache2 state=latest

   - name: Start Apache2 Ubuntu Web Server
     service: name=apache2 state=started enabled=yes

   when: ansible_os_family == "Debian"

 - block: #RedHat block

   - name: Install Httpd Web Server to Amazon Linux
     yum: name=httpd state=latest

   - name: Start Http Amazon Web Server
     service: name=httpd state=started enabled=yes

   when: ansible_os_family == "RedHat"

 - name: Generate html to redblue servers
   template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
   notify:
     - Restart Apache2
     - Restart Httpd
